### ISSUE TITLE
FileSystemException on Windows with live-reload enabled

### ISSUE THREAD

**Issue by shemminga** [quarkiverse/quarkus-web-bundler#240]
### Describe the bug

On Windows, with browser-live-reload enabled, the quarkus-web-bundler extension will try to create symlinks. Windows prohibits this for normal users.

The symlink is created here:
https://github.com/quarkiverse/quarkus-web-bundler/blob/1.5.3/deployment/src/main/java/io/quarkiverse/web/bundler/deployment/PrepareForBundlingProcessor.java#L204

Please note that the exception message below is in Dutch, because that's how Windows passes it along. I've looked up what the error message would be in English:

* Dutch: Een van de vereiste bevoegdheden is niet aan de client toegekend
* English: A required privilege is not held by the client
* Windows error code: 1314

### Expected behavior

Successful start.

### Actual behavior

An exception occurs:

```
Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor#prepareForBundling threw an exception: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
```

### How to Reproduce?

1. `quarkus.cmd create app -x quarkus-web-bundler -code`
2. `cd .\code-with-quarkus\`
3. `quarkus.cmd dev`
    * Exception: `java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: A required privilege is not held by the client` (message translated)
4. `echo 'quarkus.web-bundler.browser-live-reload=false' >> .\src\main\resources\application.properties
5. `quarkus.cmd dev`
    * Successful start

### Output of `uname -a` or `ver`

Windows 11 Pro (version 10.0.22631 N/A Build 22631)

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Quarkus version or git rev

Quarkus: 3.11.2
quarkus-web-bundler: 1.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

Full stack trace:

```
2024-06-17 03:26:52,995 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor#prepareForBundling threw an exception: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:259)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:604)
        at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:204)
        ... 10 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor#prepareForBundling threw an exception: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:259)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:604)
        at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:204)
        ... 10 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        ... 9 more
Caused by: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:259)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.nio.file.FileSystemException: C:\Users\sjoer\Documents\proj\qdemo\code-with-quarkus\target\web-bundler\dev\app\app.js: Een van de vereiste bevoegdheden is niet aan de client toegekend
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:604)
        at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
        at io.quarkiverse.web.bundler.deployment.PrepareForBundlingProcessor.prepareForBundling(PrepareForBundlingProcessor.java:204)
        ... 10 more
```

**Comment by ia3andy** [comment]
@shemminga thanks for reporting this. We've came across it during a lab, I will:
- add this info to the documentation
- catch this exception and fallback to no live-reload

We don't really have the choice about the sym-link for enabling live-reload.

**Comment by ia3andy** [comment]
@shemminga unless you want to give it a shot?

**Comment by chrisruffalo** [comment]
@ia3andy I am also experiencing this issue starting with 1.5.0.RC6 or whenever the symlinks started to be created this way. Our application environment is on windows. Is there a reason we can't catch the exception and do a copy/overwrite? Are symlinks a requirement for live reload?

**Comment by ia3andy** [comment]
> @ia3andy I am also experiencing this issue starting with 1.5.0.RC6 or whenever the symlinks started to be created this way. Our application environment is on windows. Is there a reason we can't catch the exception and do a copy/overwrite? Are symlinks a requirement for live reload?

Yes, this is what allows to detect changes on files, because the src changes, but esbuild is watching the target/web-bundler dir (which is prepared for bundling) :-/

**Comment by shemminga** [comment]
I have been exploring ways to make this work. It's a bit slow-going due to other commitments and unfamiliarity with the code base. And well, also with Quarkus. I was just playing around with it for the first time when I encountered this 😄 

I've gotten to the point where I can make changes to files in the demo project and see them live reload in the browser. Unfortunately, the unit test still fails, which could mean that I've not accounted for all scenarios yet. I haven't had time to fully debug that yet.

The approach I settled on is to have ChangeEventHandler copy changed files to the web-bundler directory. ChangeEventHandler is notified by the RuntimeUpdatesProcessor from quarkus-core-deployment. It's currently used to notify the browser of changed files _after_ esbuild did it's work, but that uses a pseudo-path and already ignores the normal updates. So it's trivial to separate the code paths for the updates before and after esbuild.

The code for this is here: https://github.com/shemminga/quarkus-web-bundler/commit/cfc2259b31b3c41e38e6cbf4419ad223dcd6406b
As mentioned, it doesn't pass tests yet, but it might be in a good enough state to spot obvious errors in thinking.

**Comment by ia3andy** [comment]
Hey @shemminga, so you idea is to fallback to using the scheduler and Quarkus scan to trigger the frontend changes?

**Comment by ia3andy** [comment]
@chrisruffalo @chrisruffalo any reason why symlinks aren't allowed on your system? because it works on Windows, just not when you don't have the right to create symlinks... is it complicated to allow them?

**Comment by ia3andy** [comment]
Could you explore something like this: https://neacsu.net/posts/win_symlinks/

**Comment by ia3andy** [comment]
@chrisruffalo @shemminga could you try this PR: https://github.com/quarkiverse/quarkus-web-bundler/pull/251 

It should gracefully fallback to using the Quarkus scheduler on Windows (or when symlink is not possible)

**Comment by ia3andy** [comment]
I am release a 1.7.0.CR1 for you to try it

**Comment by shemminga** [comment]
Thank you! I've tried it, and found something.

The exception thrown is different than the one on line 283 of PrepareForBundlingProcessor.java ( https://github.com/quarkiverse/quarkus-web-bundler/compare/main...ia3andy:quarkus-web-bundler:live-reload-fallback#diff-134bcfb852eeeef00c2ef404af6846b1702064a8e991aeb07fecd8a8ee47e6b9R283 ). Files.createSymbolicLink throws a FileSystemException.

After changing that it works, but it restarts for all changes. That works, but it would be cool to also be able to use the in-page CSS replacement of live-reload.js. A Quarkus restart breaks the Websocket connection, so live-reload.js will force-reload the page.

In my solution above I solved/worked-around that by also using the ChangeEventHandler to copy the changed files to `target/web-bundler/dev`.

**Comment by ia3andy** [comment]
> Thank you! I've tried it, and found something.
> 
> The exception thrown is different than the one on line 283 of PrepareForBundlingProcessor.java ( [main...ia3andy:quarkus-web-bundler:live-reload-fallback#diff-134bcfb852eeeef00c2ef404af6846b1702064a8e991aeb07fecd8a8ee47e6b9R283](https://github.com/quarkiverse/quarkus-web-bundler/compare/main...ia3andy:quarkus-web-bundler:live-reload-fallback#diff-134bcfb852eeeef00c2ef404af6846b1702064a8e991aeb07fecd8a8ee47e6b9R283) ). Files.createSymbolicLink throws a FileSystemException.
> 
> After changing that it works, but it restarts for all changes. 

That's great news, could you create the PR?


> That works, but it would be cool to also be able to use the in-page CSS replacement of live-reload.js. A Quarkus restart breaks the Websocket connection, so live-reload.js will force-reload the page.
>
> In my solution above I solved/worked-around that by also using the ChangeEventHandler to copy the changed files to `target/web-bundler/dev`.

The reason why I didn't retain this solution for now is that, it uses the HotDeploymentSetup scheduler to detect changes, triggering a Quarkus scan, just to copy the files, which will be detected by esbuild watched. This is too complex IMHO.

That said we could consider having a FS Watcher in the deployment part, that just copy the files on change, wdyt? The result would be even better and we could also use it for static files and all..

**Comment by ia3andy** [comment]
@all-contributors please add @shemminga  for bug, code
